version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     deploy:
      placement:
        constraints: [node.role == manager]
     environment:
       MYSQL_ROOT_PASSWORD: D@ng&rous1911
       MYSQL_DATABASE: wordpress
       MYSQL_USER: Psouza
       MYSQL_PASSWORD: D@ng&rous1911

   wordpress:
     depends_on:
       - db
     deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: Psouza
       WORDPRESS_DB_PASSWORD: D@ng&rous1911
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
